version: '2.1'
services:
    wl3:
        image: php5.6.31-apache
        build: ./apache-php
        volumes:
            - /home/andy/work/fh/apps:/var/www/html:z # all apps
            - /home/andy/work/fh/apps/volumes/apache:/etc/apache2/sites-enabled:z
            - /etc/localtime:/etc/localtime:ro # composer caching
            - /home/andy/.composer:/root/.composer:z # composer caching
              #- /home/andy/.gitconfig:/root/.gitconfig:z # Git configuration ( access alias && config )
            - /home/andy/.ssh:/root/.ssh:ro # Ssh keys for easy deployment inside the container
        environment:
            XDEBUG_REMOTE_HOST: 172.18.0.1
        networks:
            homestead:
                ipv4_address: 172.18.0.4
    mariadb:
        image: tutum/mariadb
        ports:
            - "33060:3306"
        environment:
            MARIADB_USER: admin # cannot be changed ( for info. only )
            MARIADB_PASS: root
        volumes:
            - /home/andy/work/fh/apps/volumes/mysql:/var/lib/mysql:z # database files
        networks:
            homestead:
                ipv4_address: 172.18.0.5
    
    selenium:
        image: selenium/standalone-chrome-debug
        ports:
            - 5900:5900
        networks:
            homestead:
                ipv4_address: 172.18.0.6

    nodejs:
        image: "node:6.11"
        build: ./wl3-nodejs
        working_dir: /home/node/apps
        volumes:
            - /home/andy/work/fh/apps:/home/node/apps:z # all apps
            - /etc/localtime:/etc/localtime:ro # composer caching
        environment:
            - NODE_ENV=development
        networks:
            homestead: 
                ipv4_address: 172.18.0.7

networks:
    homestead:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/24
